
// Auto generated by 'pitch-garammars'/'generate-src' script
#include "gcomm.h"
#include "JavaScriptBaseLexer.h"
#include "JavaScriptBaseParser.h"


// Generated from D:\Polydeuces\generate\JavaScriptParser.g4 by ANTLR 4.7.2


#include "JavaScriptParserListener.h"


using namespace PolydeucesEngine;

