# 'javascript-grammars\javascript\Cpp\README.md'
# 替换 this. 为 this->; 
s/this\./this->/g

# 在 options {} 段的后面加入 @header{} 段.
/options {/ {
  h
}

/}/ {
  p
  H
  g
  /options {.*}/ {
    a 
    a // Auto generated by 'pitch-garammars' script
    a @header {
    a // Auto generated by 'pitch-garammars'/'generate-src' script
    a #include "gcomm.h"
    a #include \"JavaScriptBaseLexer.h\"
    a #include \"JavaScriptBaseParser.h\"
    a }
  }
}

/}/ {
  z
  h
  d
}

/.*/ {
  H
}